### ISSUE TITLE
Parsing case class params with custom argument parsers doesn't work if defined outside of the main object.

### ISSUE THREAD

**Issue by ximik3** [com-lihaoyi/mainargs#128]
I've combined code pieces from provided examples to have something like this:
```scala
object Hello {
  implicit object DurationRead extends TokensReader.Simple[Duration] {
    def shortName = "duration"
    def read(strs: Seq[String]) = Right(Duration(strs.head))
  }

  @main
  case class Config(
    foo: Seq[String],
    myNum: Duration,
    bool: Flag
  )

  def main(args: Array[String]): Unit = {
    val config = ParserForClass[Config].constructOrExit(args)
    println(config)
  }
}
```
which works totally fine. 

However when I try to move `Config` from main `Hello` object to somewhere else it stops compiling:
```scala
object C {
  implicit object DurationRead extends TokensReader.Simple[Duration] {
    def shortName = "duration"
    def read(strs: Seq[String]) = Right(Duration(strs.head))
  }

  @main
  case class Config(
    foo: Seq[String],
    myNum: Duration,
    bool: Flag
  )
}

object Hello {
  def main(args: Array[String]): Unit = {
    val config = ParserForClass[C.Config].constructOrExit(args)
    println(config)
  }
}
```
The error is a bit misleading: `could not find implicit value for parameter tokensReader: mainargs.TokensReader[scala.concurrent.duration.Duration]`.

Is this a some kind of a limitation?
Thanks.

**Comment by lefou** [comment]
Looks like your `implicit` `TokensReaded` isn't in scope. You need to import it, e.g. with `import C.DurationRead`.

**Comment by ximik3** [comment]
Thanks you, it is working this way now.

But I think error message is still misleading since it points to `C` class instead of `Hello`. If you move `C` definition to `C.scala` you get:
```
main/scala/example/C.scala:13:20: could not find implicit value for parameter tokensReader: mainargs.TokensReader[scala.concurrent.duration.Duration]
[error]   case class Config(
```

while you actually need to add imports into `main/scala/example/Hello.scala` file instead.

**Comment by lefou** [comment]
The essential information is the line number, `.../C.scala:13:...`! That's where the compiler is expecting an implicit value but can't find one. It's pointing to a file, not a class. And your `Hello` class/object is in that file.

**Comment by ximik3** [comment]
Not exactly, my `Hello.scala`:
```scala
object Hello {
  def main(args: Array[String]): Unit = {
    import C.DurationRead
    val config = ParserForClass[C.Config].constructOrExit(args)
    println(config)
  }
}
```
and my `C.scala`:
```scala
...
object C {
  implicit object DurationRead extends TokensReader.Simple[Duration] {
    def shortName = "duration"
    def read(strs: Seq[String]) = Right(Duration(strs.head))
  }

  @main
  case class Config(
      foo: Seq[String],
      myNum: Duration,
      bool: Flag
  )
}
```

Error leads me to line 13 in `C.scala` which has nothing to do with `import C.DurationRead` in `Hello.scala`
