### ISSUE TITLE
Add support for Scala 3

### ISSUE THREAD

**Issue by jk-1** [com-lihaoyi/mainargs#17]
Scala 3 is going to include at least a subset of mainargs functionality in the future. That is certainly a good piece of news. However, the schedule is not known and the content of this subset is also unknown. 

Because of this, porting of existing Scala 2 apps using mainargs is difficult/impossible. If the Scala 3 subset of mainargs is very limited, then there is also a long term need for separate Scala 3 mainargs library.

**Comment by lolgab** [comment]
Started a port of mainargs to Scala 3 in #18 .
There is nothing that stops mainargs to support Scala 3 other than someone who implements the macros for Scala 3. Started here and slowly advancing when I have free time. Writing macros is hard and this is my first experience.
