### ISSUE TITLE
Allow hiding arguments from help

### ISSUE THREAD

**Issue by lolgab** [com-lihaoyi/mainargs#4]
It is useful, when you want to deprecate a command line argument, to hide it from the instructions given by `--help`.
I'm trying to migrate an application using `case-app` and I'm missing this feature ( done with the `@Hidden` annotation in `case-app`

**Comment by morgen-peschke** [comment]
This would also be helpful if you're doing something like this (which allows the script to know what directory it lives in):
```
#!/bin/bash

DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
exec amm "$0" --dir "$DIR" "$@"

!#

// Ammonite script follows
```

`--dir` isn't really relevant to the user, it's just plumbing, so hiding it would be ideal
